### ISSUE TITLE
Unable to perform example query

### ISSUE THREAD

**Issue by dannyfig** [guoguo12/billboard-charts#10]
Hey!

As far as I'm aware, despite successfully cloning/setup-ing, the sample case

```
>>> import billboard
>>> chart = billboard.ChartData('hot-100')
```

consistently returns a nasty 

> TypeError: 'NoneType' object is not callable

after that last line. Below is the full error trace generated after running:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-bd1122414877> in <module>()
----> 1 chart = billboard.ChartData('hot-100')

/Users/dannyvilela/Desktop/GitHub/billboard-charts/billboard.py in __init__(self, name, date, fetch, all)
    100         self.entries = []
    101         if fetch:
--> 102             self.fetchEntries(all=all)
    103 
    104     def __repr__(self):

/Users/dannyvilela/Desktop/GitHub/billboard-charts/billboard.py in fetchEntries(self, all)
    176             # Grab week data (peak rank, last week's rank, total weeks on
    177             # chart)
--> 178             peakPos = int(getRowValue('top-spot'))
    179 
    180             lastPos = getRowValue('last-week')

/Users/dannyvilela/Desktop/GitHub/billboard-charts/billboard.py in getRowValue(rowName)
    172             def getRowValue(rowName):
    173                 selector = 'div.chart-row__' + rowName + ' .chart-row__value'
--> 174                 return entry_soup.select_one(selector).string.strip()
    175 
    176             # Grab week data (peak rank, last week's rank, total weeks on

TypeError: 'NoneType' object is not callable
```

Would there happen to be a simple workaround for this particular issue? Thanks for the help!

**Comment by guoguo12** [comment]
Hey, thanks for posting this! I can't reproduce this on my machine. Can I get some info on your OS and Python version, and also how you're running this? (Are you in IPython?)

**Comment by dannyfig** [comment]
Sure thing:

OS: OSX 10.11.13
Python 3.4.4

The error occurs in both IPython and the REPL.

After some further inspection, it seems like this runs Python 2 under the hood – would a virtual environment help?

**Comment by guoguo12** [comment]
Don't think so. It should work on either Python 2 or 3.

Can you access [www.billboard.com/charts/hot-100#/charts/hot-100](this page) in your web browser?

**Comment by dannyfig** [comment]
Not sure if you meant to link to 

> https://github.com/guoguo12/billboard-charts/issues/www.billboard.com/charts/hot-100#/charts/hot-100

or just

> www.billboard.com/charts/hot-100#/charts/hot-100

If the former, no. If the latter, yes.

**Comment by guoguo12** [comment]
Oops... typo.

Hmm... I'm stumped. Try on a different computer? I'll let you know if I think of anything.

**Comment by guoguo12** [comment]
On second thought, try installing via `pip` instead of just cloning the repo. Maybe you have an unsupported version of BeautifulSoup or Requests.

**Comment by guoguo12** [comment]
Any luck @dannyfig? :)

**Comment by guoguo12** [comment]
Closing due to lack of response. Feel free to reopen if this happens again!

**Comment by jackbeckwith** [comment]
Also having this issue @guoguo12...

I'm getting the same error trace as above, with the error message "TypeError: 'NoneType' object is not callable". Any suggestions? 

Looks to me as though line 178 is causing the issue, likely because beautiful soup is finding nothing with the given selector:
`selector = 'div.chart-row__' + rowName + ' .chart-row__value'`

**Comment by jameswenzel** [comment]
@jackbeckwith are you installing `billboard.py` from pip? I'm not able to reproduce the error on either python 2.7.12 or 3.5.2 (minimum-required requests/bs4 on python2 and latest on python3). If you've installed via `pip`, maybe try upgrading bs4 and requests.

**Comment by jackbeckwith** [comment]
Thanks @jameswenzel - issue is solved. For me, updating all packages worked.

python 2.7.10 -> python 2.7.12
bs4 4.3.2 -> bs4 4.4.1
requests 2.9.1 -> 2.10.0

**Comment by guoguo12** [comment]
Interesting! I'll bump the version numbers of the dependencies up. Thanks, @jameswenzel and @jackbeckwith!
