### ISSUE TITLE
Latest commits

### ISSUE THREAD

**Issue by jameswenzel** [guoguo12/billboard-charts#11]
Billboard changed their website, so spotifyLink was broken. I fixed that, and added an additional spotifyID field. I figure that's probably more useful for the Spotify/Echo Nest APIs, since you can forgo string manipulations. I kept the same format for spotifyLink (which uses the embed.spotify URL, rather than open.spotify) since I wasn't sure if there were any dependencies on it using embed.spotify.
I also cleaned up the .to_JSON() methods since a few lines in the ChartData class were redundant. 
I tentatively bumped the version to 2.0.1. I'm sure how to go about getting that on PyPi. 
A while back I also built a BillboardIter class, which iterates over valid Billboard dates. Would anyone else find that useful? I don't think my repo listed on my github is up to date, though. Can push if there's interest.

Let me know if you think this will bring about any problems or what I can do in the future.

**Comment by guoguo12** [comment]
Thanks James! Made a few tweaks, just pushed to PyPI.

I figure that with the `previousData` attribute, users should be able to figure out how to create their own iterators. For example, here's a generator I made (from [this blog post](http://aguo.us/writings/spotify-billboard.html)) that returns the past 100 top singles:

```python
def unique_top_tracks_generator():
    seen_tracks = set()
    chart = billboard.ChartData('hot-100')  # Start at most recent

    while len(seen_tracks) < 100:
        top_track = chart[0]
        duplicate = top_track.spotifyLink in seen_tracks

        if not duplicate:
            seen_tracks.add(top_track.spotifyLink)
            yield top_track

        chart = billboard.ChartData('hot-100', date=chart.previousDate)

    raise StopIteration
```

**Comment by guoguo12** [comment]
Oh, it would be nice to have some correctness tests for `spotifyLink` and `spotifyID`. And `spotifyID` needs to be documented in the README.

**Comment by jameswenzel** [comment]
Great!
I've personally found the iterator to be really useful in quantizing any date specified (ie just using '2015-05-01' for the chart for the first week of May 2015, whether or not that's a valid date), and for grabbing charts from a range of time in the past (ie, all top songs in 2013). I agree that it is possible with `previousDate`.
I'll see about adding/fixing the tests + docs later today.

**Comment by guoguo12** [comment]
Oops, just noticed this issue was still open.

On second thought, quantization alone is useful. Maybe the `ChartData` constructor should have an optional parameter `quantize=True` that indicates whether to attempt to quantize the given date, e.g. by looking up to 6 days in the past. Or maybe that should be something like `quantizeDays=6`. Thoughts?

**Comment by jameswenzel** [comment]
Quantization is definitely handy, which is half of why I built the iterator. The good thing about Billboard charts is that they're _always_ 7 days after the last one (even with release-date changes).
I figured it was a lot quicker to just calculate that from the start date (1958-08-09) each time than to load/parse each page - unless you can think of any math workarounds for calculating that (counting just weeks since then might be straightforward).
Right now it's not smart enough to quantize a single date alone (eg 2015-01-01 won't quantize to 2015-01-03 or 2014-12-27), but it'd be pretty easy to write that feature into it. It's probably wise to quantize _forward_ rather than backward, because billboard charts are always marked ahead of the current date (the current charts are dated July 23rd).

**Comment by guoguo12** [comment]
> they're *always* 7 days after the last one (even with release-date changes)

Whoa, really? I didn't know that! It makes things a lot nicer if we assume/hardcode that a chart is released every seven days.

> I figured it was a lot quicker to just calculate that from the start date (1958-08-09) each time

This might be the easiest way. Definitely downloading/parsing up to 7 pages isn't the way to go.

> It's probably wise to quantize *forward* rather than backward

Good thinking!

Do you think quantization should be the default behavior of the ChartData constructor? I.e., would it make sense for the ChartData constructor to always succeed, as long as the given date is between the earliest chart date and the newest chart date?

**Comment by jameswenzel** [comment]
Yeah, I've pulled their charts back to 1958 using my ChartDateIter with no gaps. Even when they changed the global release date to Friday, the dating scheme stayed the same (which surprised me).

Quantization should probably be the default behavior - I think it's pretty intuitive. If you're curious about the top songs on 2015-01-01, you probably don't care if the chart is dated 2015-01-03. Either way, it beats guessing until you hit something.

**Comment by guoguo12** [comment]
Okay, sounds good. So basically, always round up to the nearest Saturday? That should be fairly easy using Python's `datetime`.

**Comment by jameswenzel** [comment]
It's a little more complicated than that... [Here's](http://www.billboard.com/articles/columns/chart-beat/6605842/billboard-alter-chart-tracking-week-global-release-date) a summary of Billboard's current methodology.
Depending on how consistent you want it to be:
Charts go up Tuesday morning (when?) and are dated two-saturdays afterwards. Eg July 14th's chart is dated July 25th. So there should be some math to make sure the same chart is given depending on the query. If I load `ChartData('hot-100', '2016-07-12')` _tomorrow_, it should probably give the same chart as calling `ChartData('hot-100')` _today_. So I guess a Tuesday/afternoon? check would give consistent results. 
Still pretty simple, just another layer to consider.

**Comment by guoguo12** [comment]
I see, thanks for the link.

> If I load `ChartData('hot-100', '2016-07-12')` _tomorrow_, it should probably give the same chart as calling `ChartData('hot-100')` _today_.

Maybe it'd be okay if this isn't true. Maybe `ChartData('hot-100')` should just return the latest chart, whereas `ChartData('hot-100', date=DATE)` should return the chart for `DATE`, rounding up to the nearest Saturday. Thoughts?

**Comment by guoguo12** [comment]
Closing this. @jameswenzel and I decided to follow the same rounding rules that Billboard.com uses (always round up to the nearest Saturday).
