### ISSUE TITLE
SpotifyID populated when page shows no active link

### ISSUE THREAD

**Issue by dbfowler** [guoguo12/billboard-charts#14]
Came across this problem when trying to create a unique song ID for tracks. Essentially, some tracks are assigned a SpotifyID that does not necessarily refer to that track. Here's an example:
"Mine" by Beyonce featuring Drake has no active "Listen on Spotify" link: http://www.billboard.com/charts/hot-100/2014-01-11 but the HTML stores an ID anyways: 

`<article class="chart-row row-new chart-row--99 js-chart-row" data-hovertracklabel="Song Hover-Mine" data-songtitle="" data-spotifyType="track" data-spotifyUri="track:0dBW6ZsW8skfvoRfgeerBF" data-spotifyId="0dBW6ZsW8skfvoRfgeerBF">`

This particular ID corresponds to Mine by Taylor Swift - clearly an issue stemming from Billboard itself. Not sure if there is a way to control for this in the billboard.py script.

**Comment by guoguo12** [comment]
Wow, good find! I can't think of a good way of detecting this from billboard.py. It looks like the HTML for the green Spotify button is still present on the page. I think they have JavaScript (hardcoded maybe?) that hides it when the page loads.

Let me know if you have any ideas.

**Comment by jameswenzel** [comment]
Looks like the JavaScript manually inserts a `data-spotifyPreview="yes"` tag if it's the correct ID. But that's post-load, unfortunately. Looking at the source, almost looks like they're programmatically getting Spotify IDs and then comparing them to a master chart of known good IDs... which doesn't really make sense? The code's uglified so I could be wrong.

**Comment by guoguo12** [comment]
@jameswenzel Thanks for digging into the front-end code. Now I'm curious how they validate Spotify IDs. 

@dbfowler Closing this as a "won't fix" issue. There doesn't seem to be much we can do. Thanks for reporting it though!
