### ISSUE TITLE
'spotify-rewind' chart does not work

### ISSUE THREAD

**Issue by chrisamow** [guoguo12/billboard-charts#15]
thx for the nice work btw
I'm using python3.6 and
billboard.py==3.0.2
Maybe formatting is unconventional / not what you were expecting, looking at
http://www.billboard.com/charts/spotify-rewind

```
In [1]: import billboard

In [2]: ch = billboard.ChartData('spotify-rewind')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-7e40362569e4> in <module>()
----> 1 ch = billboard.ChartData('spotify-rewind')

/home/chris/anaconda3/lib/python3.6/site-packages/billboard.py in __init__(self, name, date, fetch, all, quantize)
    114         self.entries = []
    115         if fetch:
--> 116             self.fetchEntries(all=all)
    117 
    118     def __repr__(self):

/home/chris/anaconda3/lib/python3.6/site-packages/billboard.py in fetchEntries(self, all)
    209             # Grab week data (peak rank, last week's rank, total weeks on
    210             # chart)
--> 211             peakPos = int(getRowValue('top-spot'))
    212 
    213             lastPos = getRowValue('last-week')

/home/chris/anaconda3/lib/python3.6/site-packages/billboard.py in getRowValue(rowName)
    205             def getRowValue(rowName):
    206                 selector = 'div.chart-row__' + rowName + ' .chart-row__value'
--> 207                 return entrySoup.select_one(selector).string.strip()
    208 
    209             # Grab week data (peak rank, last week's rank, total weeks on

AttributeError: 'NoneType' object has no attribute 'string'
```

**Comment by guoguo12** [comment]
Hey, thanks for the bug report! Yep, it's not the same format as most other charts. I'm not sure if I want to support this one. @jameswenzel, what do you think?

In any case, I'll add a note to the readme!

**Comment by jameswenzel** [comment]
This is actually a really interesting chart! However, I suspect this is part of a temporary partnership between Spotify and Billboard, and I sort of doubt it'll be around indefinitely. So not sure how interesting/useful the dataset will be over the long run. It would definitely require special handling and probably a new class and, which might be more effort than its worth, given that it might not be around in a year or two.

**Comment by guoguo12** [comment]
Well said. Closing for now. Thanks again @chrisamow, and let me know if you have any further suggestions.

**Comment by chrisamow** [comment]
Ok, thx guys - I'll put some better error handling in, but it might help yourselves out if you have a separate exception thrown for scraping/breakage errors (expected from time to time) vs other errors that are actually problems.  Cheers!

**Comment by guoguo12** [comment]
Agreed, thanks!
