### ISSUE TITLE
error retrieving chart "greatest-hot-100-singles" "greatest-country-songs" etc

### ISSUE THREAD

**Issue by lohriialo** [guoguo12/billboard-charts#19]
Here's the trace log:

`chart = billboard.ChartData('greatest-hot-100-singles')
  File "C:\Users\username\PycharmProjects\project\env\lib\site-packages\billboard.py", line 116, in __init__
    self.fetchEntries(all=all)
  File "C:\Users\username\PycharmProjects\project\env\lib\site-packages\billboard.py", line 211, in fetchEntries
    peakPos = int(getRowValue('top-spot'))
  File "C:\Users\username\PycharmProjects\project\env\lib\site-packages\billboard.py", line 207, in getRowValue
    return entrySoup.select_one(selector).string.strip()`
`AttributeError: 'NoneType' object has no attribute 'string'`

**Comment by guoguo12** [comment]
Thanks @lohriialo! Looks like it's because they don't have peak/last position data.

@jameswenzel: Is the right thing to do here 1) not support charts like this or 2) put the code for getting peak/last position data, change, etc. in a try-catch and allow them to be `None`?

**Comment by jameswenzel** [comment]
Yeah, really just need to just wrap `getRowValue` in a try/catch or if/else.

**Comment by guoguo12** [comment]
Addressed in fcae8724d06fc60e68f2ac1671328d70ed21bede. Will be included in next release.
