### ISSUE TITLE
please add support for billboard.com/chart/artist-100

### ISSUE THREAD

**Issue by lohriialo** [guoguo12/billboard-charts#20]
currently 'artist-100' chart isn't supported, kindly add support

```
chart = billboard.ChartData('artist-100')
File "C:\Users\username\PycharmProjects\project\env\lib\site-packages\billboard.py", line 116, in __init__
self.fetchEntries(all=all)
File "C:\Users\username\PycharmProjects\project\env\lib\site-packages\billboard.py", line 200, in fetchEntries
if (basicInfoSoup[3].find('a')):

IndexError: list index out of range
```

**Comment by fhopp** [comment]
Not sure what happened there, but the current error looks like this: 
//chart = billboard.ChartData('artist-100')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/anaconda3/envs/lyrics_analysis/lib/python3.6/site-packages/billboard.py in fetchEntries(self)
    166             try:
--> 167                 title = basicInfoSoup[1].string.strip()
    168             except:

AttributeError: 'NoneType' object has no attribute 'strip'

During handling of the above exception, another exception occurred:

BillboardParseException                   Traceback (most recent call last)
<ipython-input-40-137c54ce0515> in <module>()
----> 1 chart = billboard.ChartData('artist-100')

~/anaconda3/envs/lyrics_analysis/lib/python3.6/site-packages/billboard.py in __init__(self, name, date, fetch)
    106         self.entries = []
    107         if fetch:
--> 108             self.fetchEntries()
    109 
    110     def __repr__(self):

~/anaconda3/envs/lyrics_analysis/lib/python3.6/site-packages/billboard.py in fetchEntries(self)
    168             except:
    169                 message = "Failed to parse title"
--> 170                 raise BillboardParseException(message)
    171 
    172             try:

BillboardParseException: Failed to parse title//

**Comment by laismota** [comment]
Yes, the same error here. It would be great if it 'artist-100' was supported.

The error here is something like this:
```
Traceback (most recent call last):
  File "crawler_artists_hot100.py", line 7, in <module>
    chart = billboard.ChartData('artist-100', date="2017-10-21")
  File "/usr/local/lib/python2.7/dist-packages/billboard.py", line 108, in __init__
    self.fetchEntries()
  File "/usr/local/lib/python2.7/dist-packages/billboard.py", line 170, in fetchEntries
    raise BillboardParseException(message)
billboard.BillboardParseException: Failed to parse title
```
