### ISSUE TITLE
Spotify ID is gone

### ISSUE THREAD

**Issue by carlosedp** [guoguo12/billboard-charts#21]
I had a script that parsed info from Billboard as well and for what I see the Spotify ID for each song is gone.

**Comment by AkshayPall** [comment]
Same issue here. Just ran my update script and noticed the issue.

**Comment by guoguo12** [comment]
Thanks for the heads up. Anyone know how recently they made this change?

**Comment by lohriialo** [comment]
I also ran into this problem today, billboard.com seem to have removed the spotifyID/spotifyLink for all dates.

Because If I ran the example /examples/top-singles-playlist, it while loops forever which means the chart.previousDate also doesn't contain spotifyID/spotifyLink data anymore

**Comment by carlosedp** [comment]
Yes, I made a parser to match the song and search Spotify but it's not too effective.. take a look on my repo.
https://github.com/carlosedp/billboard-spotify
It's the search_matched_song function.
