### ISSUE TITLE
Problem when going backwards in time

### ISSUE THREAD

**Issue by PCA2017** [guoguo12/billboard-charts#23]
I want to get all billboard charts up to a certain date.

My code looks like this:
 
        chart = billboard.ChartData('hot-100')
        year = int(chart.date[:4])

        while year >= 1995:
            print(year)
            print(chart.date)

            # Get older chart
            chart = billboard.ChartData('hot-100', date=chart.previousDate)
            year = int(chart.date[:4])

Sadly i get an output like this:
...
2014
2014-03-15
2014
2014-03-08
2017
2017-12-09
2017
2017-12-02
...

or
...
2013
2013-10-12
2013
2013-10-05
2017
2017-12-09
...

-> It switches back to the latest one but the exact date of chart where this happens differs.
Any idea on how i could fix this?

**Comment by guoguo12** [comment]
Hey, thanks for reporting this! I was able to reproduce it using your code.

I'm guessing that the date of the previous week's chart can't be found for some reason. (In which case `self.previousDate` defaults to `None`, and passing `None` as the second argument to `ChartData` causes the API to fetch the current week's chart.)

 The fact that this is apparently non-deterministic troubles me.

Can I suggest you try again, but this time put a mild timeout between calls to `ChartData`? My guess is that Billboard throttles requests after a while and serves an error page.

I'll take a closer look when I have time.

**Comment by guoguo12** [comment]
By the way, because of some poor design decisions I made in the past, bad requests fail silently:

```
>>> ChartData('hot-1000000', date='helloworld')
hot-1000000 chart from helloworld
---------------------------------
```

So you might want to check that the last request with the correct date (in your example above, 2013-10-05) actually completed successfully (e.g., you can check that the length is 100 and retry if it isn't).

**Comment by PCA2017** [comment]
Yes this seems to be the solution! Replaced the last part in the loop.

        # Get older chart
        older_chart = billboard.ChartData('hot-100', date=chart.previousDate)
        while len(older_chart)!=100:
            time.sleep(2)
            older_chart = billboard.ChartData('hot-100', date=chart.previousDate)
            
        chart = older_chart
        year = int(chart.date[:4])
