### ISSUE TITLE
Fetching wrong dates sometimes doesn't round, sometimes it does.

### ISSUE THREAD

**Issue by theruan** [guoguo12/billboard-charts#29]
quote from comment on Billboard.py" date: The chart date, as a string in YYYY-MM-DD format.
                By default, the latest chart is fetched.
                >>>If the argument is not a date on which a chart was published,
                >>>Billboard automatically rounds dates up to the nearest date on
                >>>which a chart was published."
This behavior doesn't happen, dont know if it ever did cause i just started using it, but trying to use a few dates like 2017-12-12 or 2017-12-19 end on no results, billboard site doesn't change to the nearest result if the date input is done through the address don't know if they changed the behavior on that, this happens only if the wrong date is put on the site's search field, then it moves to the next available chart.

**Comment by theruan** [comment]
I just rechecked it and for 2017-12-19 and it fetched the next chart, gonna check again later today.

**Comment by guoguo12** [comment]
Hey, thanks for reporting this! I just added [a test](https://github.com/guoguo12/billboard-charts/blob/b7a6fb9646367eb929a4e6fc2f61d29108c81a8d/tests/test_dates.py#L15) for rounding. Let me know if you experience the bug again.

**Comment by guoguo12** [comment]
Closing this for now.
