### ISSUE TITLE
SpotifyIDs for version 3.0.2

### ISSUE THREAD

**Issue by OmK1103** [guoguo12/billboard-charts#32]
So I am trying to get the spotify IDs of the billboard songs, and it looks like version 3.0.2 had a 'spotifyID' attribute for every song instance in the billboard chart instance. Is it possible to get that again? Also, the spotify IDs are unavailable for almost all the songs I searched for. It would help me a lot if getting the spotify IDs is possible again.

**Comment by guoguo12** [comment]
This isn't possible because Billboard doesn't include Spotify data with their charts anymore (last I checked). Sorry!

**Comment by guoguo12** [comment]
Another user mentioned a possible workaround at #21. Might want to check it out.

**Comment by OmK1103** [comment]
Thanks, and apologies for the late response!
