### ISSUE TITLE
Use __str__ for pretty-printing entries, and __repr__ for object representation

### ISSUE THREAD

**Issue by victor-lin** [guoguo12/billboard-charts#41]
[Documentation for `__repr__`](https://docs.python.org/2/library/functions.html#repr):
> this function makes an attempt to return a string that would yield an object with the same value when passed to eval()

[Documentation for `__str__`](https://docs.python.org/2/library/functions.html#str):
> Return a string containing a nicely printable representation of an object.

Currently, calling `str()` or `print` on a `ChartData` invokes `__repr__` since `__str__` is not implemented.

Instead, `__repr__` could return a representation of the chart object (with corrected dates), and the current code can be used for `__str__`. Maybe the following the behavior:

    > chart = billboard.ChartData('hot-100', date='1996-07-30')
    > print repr(chart)
    billboard.ChartData('hot-100', date='1996-08-03')
    > print chart
    hot-100 chart from 1996-08-03
    -----------------------------
    1. ‘Macarena (Bayside Boys Mix)’ by Los Del Rio
    ...

Should be an easy fix. Let me know if this is a good idea, and I can go ahead and implement it.

**Comment by guoguo12** [comment]
Thanks! Yep, I think this is a good idea. It'd be great if you could implement it!

**Comment by guoguo12** [comment]
Resolved in #42. Thanks @victor-lin!
