### ISSUE TITLE
Empty chart data

### ISSUE THREAD

**Issue by jeffjc97** [guoguo12/billboard-charts#44]
In trying to access any chart (I've tried hot-100 and pop-songs) for any date (current, or dates in the past), the result is always an empty chart. Do you know what could be causing this? I've used this library in the past successfully, so I'm not sure why the same code doesn't seem to be returning anything.

Here's an example of what I'm running
```
chart = billboard.ChartData('pop-songs', date='2015-11-28')
print chart
```

and the response
```
pop-songs chart from 2015-11-28
-------------------------------
```

**Comment by guoguo12** [comment]
What version are you using? Billboard recently updated their UI, breaking older versions of the library.

**Comment by jeffjc97** [comment]
Agh I just updated and it worked fine! Can't believe I forgot to try updating. Thanks for maintaining this package!

**Comment by guoguo12** [comment]
No problem! It's definitely been a team effort.

**Comment by mcookhome** [comment]
our humble leader right there ^
