### ISSUE TITLE
Incorrect values for songs debuting at number 1

### ISSUE THREAD

**Issue by becausealice2** [guoguo12/billboard-charts#49]
From line 246 in billboard.py:
>`# if there is no div with class div.chart-number-one__last-week, that means it was the top song the prior week`

This is incorrectly returning `False` for isNew and `1` for lastPos on songs debuting at number 1.

[Songs debuting at number 1](https://www.billboard.com/charts/hot-100/2018-05-19) have a star shaped badge that say 'NEW' with a CSS selector `img.chart-number-one__stats-cell-new`. Perhaps, check for this in the absence of `div.chart-number-one__last-week` before assigning those values?

**Comment by guoguo12** [comment]
Fixed in 5.0.1. Thanks for reporting this!
