### ISSUE TITLE
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url

### ISSUE THREAD

**Issue by xfalcon727** [guoguo12/billboard-charts#59]
Hi, i'm getting Forbidden for url errors when i try to access a chart.

billboard.ChartData('hot-100')

gives me the error.

Does this package still work?

**Comment by jameswenzel** [comment]
You should upgrade to `5.2.3` with `pip install billboard.py --upgrade`, #57

**Comment by biosparky** [comment]
> You should upgrade to `5.2.3` with `pip install billboard.py --upgrade`, #57

sweet..tncs
