### ISSUE TITLE
HTTPError: 429 Client Error: Too Many Requests for url: http://www.billboard.com/charts/

### ISSUE THREAD

**Issue by Sevena713** [guoguo12/billboard-charts#64]
Hi!
I was trying to extract charts data but the error happened after extracting 10 weeks data.
Is it possible to be fixed?

**Comment by guoguo12** [comment]
Does throttling your requests help?

**Comment by asharp02** [comment]
@guoguo12 So I also ran into this issue when trying to download Billboard charts for consecutive weeks. I tried using `time.sleep` but was basically just guessing as to how many seconds to sleep and how often. What are your thoughts on handling this in `fetchEntries()`? I was thinking in the case of a 429 response, we grab the `Retry-After` header from the response and add a `time.sleep` for that length of time. That way, the process doesn't just error out when trying to make consecutive requests. If this sounds good to you, I would be happy to submit a PR :)

**Comment by guoguo12** [comment]
That'd be great! Do they send a `Retry-After` header?

**Comment by asharp02** [comment]
Sounds good, I'll get started then 👍 From what I can tell, yes. Just doing `req.headers.get("Retry-After")` on the response obj in `fetchEntries()` gives me a number (if given a 429 status code).

**Comment by guoguo12** [comment]
Closing this because #65 was merged. Feel free to reopen if you see this again.
