### ISSUE TITLE
Meaning of peakPos

### ISSUE THREAD

**Issue by critmcdonald** [guoguo12/billboard-charts#66]
A minor thing, but I think the description of `peakPos` on the README is confusing and perhaps incorrect. It is described as "The track's peak position on the chart at any point in time, **including future dates**, as an int (or None if the chart does not include this information)." I think it is the peak position as of the week the chart was published. Otherwise pulling a past chart would show a higher peak position when the track first enters the chart. Maybe it should be "highest position track has reached as of chart date".

| date       | title                   | artist | current | previous | peak | weeks |
|------------|-------------------------|--------|--------:|---------:|-----:|------:|
| 2013-02-23 | Started From The Bottom | Drake  |      63 |        0 |   63 |     1 |
| 2013-03-02 | Started From The Bottom | Drake  |      10 |       63 |   10 |     2 |
| 2013-03-09 | Started From The Bottom | Drake  |       6 |       10 |    6 |     3 |
| 2013-03-16 | Started From The Bottom | Drake  |       6 |        6 |    6 |     4 |
| 2013-03-23 | Started From The Bottom | Drake  |       7 |        6 |    6 |     5 |
| 2013-03-30 | Started From The Bottom | Drake  |       6 |        7 |    6 |     6 |
| 2013-04-06 | Started From The Bottom | Drake  |       7 |        6 |    6 |     7 |
| 2013-04-13 | Started From The Bottom | Drake  |       8 |        7 |    6 |     8 |
| 2013-04-20 | Started From The Bottom | Drake  |       9 |        8 |    6 |     9 |
| 2013-04-27 | Started From The Bottom | Drake  |       9 |        9 |    6 |    10 |

**Comment by guoguo12** [comment]
Thanks for pointing this out!

The buggy description dates back to August 2017 (#22). Presumably Billboard silently changed (fixed) their peak position numbers sometime since then.

I'll update the description.
