### ISSUE TITLE
Specify a year

### ISSUE THREAD

**Issue by Shinyhero36** [guoguo12/billboard-charts#69]
Hi, 
I have this code bellow which shows the billboard for the pop songs:
```python
from billboard import charts
from billboard import ChartData
from pprint import pprint

chart = ChartData('pop-songs')
```
Is it possible to specify a year for instance: pop-songs of 2019
![image](https://user-images.githubusercontent.com/36128190/82803022-1abfc780-9e80-11ea-9f8c-efa86e18ddb1.png)

And also how can i get the `hot-100` of a specific `decade-end`?

**Comment by guoguo12** [comment]
#34 or #47 might work. The library doesn't officially support it yet.
