### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by jonigl** [guoguo12/billboard-charts#7]
I have a problem using this script:

$ python
Python 2.7.10 (default, Oct 23 2015, 18:05:06)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import billboard
>>> chart = billboard.ChartData('hot-100')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/billboard.py", line 104, in __init__
    self.fetchEntries(all=all)
  File "/Library/Python/2.7/site-packages/billboard.py", line 155, in fetchEntries
    basicInfoSoup = entry_soup.find('div', 'row-title').contents
AttributeError: 'NoneType' object has no attribute 'contents'

I don't know what is the problem. Help please.

Thanks in advance.

**Comment by guoguo12** [comment]
Hey, thanks for reporting this. It looks like the website layout has changed since the tests were last run. I'll look into it.

**Comment by guoguo12** [comment]
Yep, it looks like Billboard.com recently changed their CSS class names to be [BEM](https://css-tricks.com/bem-101/)-like.

Everything should now be fixed. I just pushed the new version (v1.0.3) to PyPI, so go ahead and upgrade with `pip install --upgrade billboard.py`.

**Comment by jonigl** [comment]
Hey @guoguo12 thanks a lot. Works like a charm!

**Comment by guoguo12** [comment]
No problem! :) If you don't mind me asking, what are you using this library for?

**Comment by jonigl** [comment]
Yeah! I'll use it in my work to get all weeks hot-100 from the very beginning to these days, so then put this data into a DB :)

**Comment by guoguo12** [comment]
Ah okay. Very cool stuff!

**Comment by jonigl** [comment]
:+1:
