### ISSUE TITLE
_parseNewStylePage fails bc of previousDate

### ISSUE THREAD

**Issue by recluse27** [guoguo12/billboard-charts#73]
Hello @guoguo12 

`_parseNewStylePage` fails bc of `previousDate` parsing part (need to change an html selector) [line 276]
I raised a [https://github.com/guoguo12/billboard-charts/pull/72](pr) to fix the issue. Please, take a look and merge. Feel free to ask questions.

Sincerely,
VL

**Comment by guoguo12** [comment]
Merged, thanks!
