### ISSUE TITLE
API suddenly not work!

### ISSUE THREAD

**Issue by JinSolChoi** [guoguo12/billboard-charts#74]
Hello! I'm using billboard-charts API every week.
Yesterday I heard billboard updated new chart 'global 200 chart', so I try to check it.
But when I call the chart for example `billboard.ChartData('hot-100)`, then error occured.

**KeyError: 'data-previous-chart-date'**

Anyone can solve this problem? 
Thank u

**Comment by recluse27** [comment]
Hello @JinSolChoi,

Thank you for your message.
Please, update the library to the latest version. This issue was fixed 2 days ago.
Please, feel free to contact us if you need any further assistance.

Sincerely,
VL

**Comment by JinSolChoi** [comment]
Thank you so much!

**Comment by darcowski** [comment]
Updating didnt solve the problem!
