### ISSUE TITLE
API doesnt work

### ISSUE THREAD

**Issue by darcowski** [guoguo12/billboard-charts#75]
This still doesnt work, even after installing new version

Hello! I'm using billboard-charts API every week.
Yesterday I heard billboard updated new chart 'global 200 chart', so I try to check it.
But when I call the chart for example billboard.ChartData('hot-100), then error occured.

KeyError: 'data-previous-chart-date'

Anyone can solve this problem?
Thank u

**Comment by recluse27** [comment]
Hello @darcowski,

You have the same issue as [https://github.com/guoguo12/billboard-charts/issues/74](url).
Please, update the library to the version 6.1.2.

Don't hesitate to contact us if you can't resolve it.

Sincerely,
VL
