### ISSUE TITLE
Charts relying on "old style" parsing missing previousDate & nextDate at extremes

### ISSUE THREAD

**Issue by johnwmillr** [guoguo12/billboard-charts#78]
Hi Allen,

I believe I found a bug relating to the `previousDate` and `nextDate` values of `ChartData` for charts that rely on the old-style page parsing.

When an old-style chart parses either its oldest or newest page, the `previousDate` and `nextDate` values (respectively) will be missing from the `ChartData` object, rather than being set to `''` or `None`.

**Missing `previousDate`**

```python
chart = billboard.ChartData("country-songs", date="1958-10-20")
chart.previousDate
```

>AttributeError                            Traceback (most recent call last)
>\<ipython-input-52-b3eed127b189\> in \<module\>
>----> 1 chart.previousDate
>
>AttributeError: 'ChartData' object has no attribute 'previousDate'

**Missing `nextDate`**
```python
chart = billboard.ChartData("country-streaming-songs", date="2020-10-31")
chart.nextDate
```

>AttributeError                            Traceback (most recent call last)
>\<ipython-input-56-3564beeeeb8c\> in \<module\>
>----> 1 chart.nextDate
>
>AttributeError: 'ChartData' object has no attribute 'nextDate'

**Correctly function new-style chart**
```python
chart = billboard.ChartData("hot-100", date="1958-08-04")
chart.previousDate
```

> ''

I can put together a PR for this in the next couple of days. It should be a fairly straightforward fix.

**Comment by guoguo12** [comment]
Agreed, that's a bug. Thanks for reporting this!
