### ISSUE TITLE
This API NOT WORK NOW!

### ISSUE THREAD

**Issue by JinSolChoi** [guoguo12/billboard-charts#86]
This API not work now.
I think it;s because of billboard chart web site update.
Can you please check this issue?

**Comment by HowlingWolf7** [comment]
I'm getting the same issue this morning.
Taking a look at where is broke on my instance was at the triple asterisk line within the below definition.

    def _parseNewStylePage(self, soup):
        dateElement = soup.select_one("button.date-selector__button.button--link")
        if dateElement:
            dateText = dateElement.text.strip()
            curDate = datetime.datetime.strptime(dateText, "%B %d, %Y")
            self.date = curDate.strftime("%Y-%m-%d")

    ***self.previousDate = soup.select_one("#charts")["data-chart-prev-date"]***
        self.nextDate = soup.select_one("#charts")["data-chart-next-date"]

        for entrySoup in soup.select("li.chart-list__element"):

**Comment by marco97pa** [comment]
Duplicate: https://github.com/guoguo12/billboard-charts/issues/85

**Comment by guoguo12** [comment]
Should be fixed in 7.0.0. See #85 for details.

**Comment by JinSolChoi** [comment]
I upgraded but some code had issue.
"billboard.charts()"n or billboard.charts()[0]"... is not work now.
Can you please check this?

**Comment by guoguo12** [comment]
That function no longer exists.
