### ISSUE TITLE
Not able to pull metadata for new TikTok charts

### ISSUE THREAD

**Issue by trilliamn** [guoguo12/billboard-charts#92]
Getting an error when I try to use 'tiktok-billboard-top-50' as chart name. Might be due to new metadata structure to the latest charts added.

**Comment by iamrhyot** [comment]
same. still doesn't appear to be a solution for this yet.

**Comment by italoaa** [comment]
I did a super small fix #94 where you just need to comment the raise error line. Not permanent at all but works for now. And it is not probable this module will get any updates soon

**Comment by cycomachead** [comment]
See #95 now for an alternate solution.

**Comment by guoguo12** [comment]
Fixed by @cycomachead! Thanks!

**Comment by guoguo12** [comment]
Specifically, it's fixed in the version I just uploaded to PyPI (7.1.0).
